// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkzIorPP71YumFue0zxDJrTBoNM8D_VK8',
    appId: '1:348570107821:web:97b31e0089b6696e946b24',
    messagingSenderId: '348570107821',
    projectId: 'futbol-6ef6e',
    authDomain: 'futbol-6ef6e.firebaseapp.com',
    storageBucket: 'futbol-6ef6e.appspot.com',
    measurementId: 'G-613PG2ZNLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP7icAkdcET48jX4lG4bNkPj5awxo3EhM',
    appId: '1:348570107821:android:da1f84f9162103fa946b24',
    messagingSenderId: '348570107821',
    projectId: 'futbol-6ef6e',
    storageBucket: 'futbol-6ef6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFczUb6uWYz72D4w3TzVF3WJITItGDbJg',
    appId: '1:348570107821:ios:32d8d697a7a3ae99946b24',
    messagingSenderId: '348570107821',
    projectId: 'futbol-6ef6e',
    storageBucket: 'futbol-6ef6e.appspot.com',
    iosClientId: '348570107821-c48pi39p3aau4etqv8ghdivm4j73ko0e.apps.googleusercontent.com',
    iosBundleId: 'senizleyeterki.tv.byneo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFczUb6uWYz72D4w3TzVF3WJITItGDbJg',
    appId: '1:348570107821:ios:32d8d697a7a3ae99946b24',
    messagingSenderId: '348570107821',
    projectId: 'futbol-6ef6e',
    storageBucket: 'futbol-6ef6e.appspot.com',
    iosClientId: '348570107821-c48pi39p3aau4etqv8ghdivm4j73ko0e.apps.googleusercontent.com',
    iosBundleId: 'senizleyeterki.tv.byneo',
  );
}
